#!/bin/bash

DATE=$(date '+%F')
TIME=$(date '+%H%M%S')

PARKRUN_DATA=${PARKRUN_DATA:-$HOME/parkrun/data}

mkdir -p "${PARKRUN_DATA}/${DATE}"

./get-barcodes.py | ./format-barcodes.pl >"${PARKRUN_DATA}/$DATE/barcodes-$TIME"


