#!/bin/bash

DATE=$(date '+%F')
TIME=$(date '+%H%M%S')

PARKRUN_DATA=${PARKRUN_DATA:-$HOME/parkrun/data}

mkdir -p "${PARKRUN_DATA}/${DATE}"

./get-times.py | ./format-times.pl >"${PARKRUN_DATA}/$DATE/times-$TIME"


